name: test
on:
  push:
    branches:
      - "master"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: make setup
      - name: Run Linters
        run: make lint
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
          cache: 'pip'
      - name: Install dependencies
        run: |
          make setup
          pip install tox-gh
      - name: Run tests
        run: tox -m ci
        env:
          PYTEST_ADDOPTS: "--no-header -vv -rN"
